name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/book:latest

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Write environment variables to .env file on server
            echo "${{ secrets.ENV_FILE }}" > /home/${{ secrets.SERVER_USER }}/book.env

            # Pull latest image
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/book:latest

            # Stop and remove old container if exists
            if [ "$(sudo docker ps -q -f name=book)" ]; then
              sudo docker stop book
            fi
            if [ "$(sudo docker ps -aq -f name=book)" ]; then
              sudo docker rm book
            fi

            # Run container with .env file
            sudo docker run -d \
              --name book \
              --env-file /home/${{ secrets.SERVER_USER }}/book.env \
              -p 8000:8000 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/book:latest
