name: CI
on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
              image: postgres:16
              env:
                  POSTGRES_DB: bookshop
                  POSTGRES_USER: admin_user
                  POSTGRES_PASSWORD: 1234
              options: >-
                  --health-cmd pd_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5
        env:
            DB_NAME: bookshop
            DB_USER: admin_user
            DB_PASSWORD: 1234
            DB_HOST: postgres
            DB_PORT: 5432

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tests
              run: |
                  python manage.py test